"""
If you are better with Python data types than JSON directly
You can use this pyhton file to generate the JSON"
"""

portfolio = {"person": {"name": "Hofecker Andor",
                        "birth": "03.06.1989",
                        "nation": "HU",
                        "contact_info":
                            {"E-mail": "hof.and.or@gmail.com",
                             "Phone": "+36 (20) 965 7032",
                             "LinkedIn": "https://www.linkedin.com/in/andor-hofecker-58887791/",
                             "Kaggle": "https://www.kaggle.com/andorhofecker",
                             },
                        "languages": {"Hungarian": "native",
                                      "English": "fluent",
                                      "French": "basic"},
                        "hobbies": ["analog_photography",
                                    "videography",
                                    "prototyping",
                                    "running",
                                    "cycling",
                                    "painting"],
                        },
             "projects": [{"title": "Mechatronical Engineering BSc (BUTE, 2013)",
                           "subtitle": "Power electronics specialization",
                           "group": "Studies",
                           "link": None,
                           "image": None,
                           "tags": ["University",
                                    "BSc",
                                    "mechatronics",
                                    "BUTE",
                                    "final_project",
                                    "power_electronics"],
                           },
                          {"title": "Mechatronical Engineering MSc (BUTE, 2016)",
                           "subtitle": "Intelligent embedded systems specialization",
                           "group": "Studies",
                           "link": None,
                           "image": None,
                           "tags": ["University",
                                    "BSc",
                                    "mechatronics",
                                    "BUTE",
                                    "diploma",
                                    "intelligent",
                                    "embedded"],
                           },
                          {"title": "Machine learning by Stanford University",
                           "supertitle": "Coursera",
                           "group": "Online course",
                           "link": "https://www.coursera.org/account/accomplishments/verify/4SUDQ7KCLJK8",
                           "image": None,
                           "tags": ["machine_learning",
                                    "Matlab",
                                    "Stanford",
                                    "Coursera",
                                    "Andrew_Ng"],
                           },
                          {"title": "Deep learning specialization by deeplearning.ai",
                           "supertitle": "Coursera",
                           "group": "Online course",
                           "link": "https://www.coursera.org/account/accomplishments/specialization/JLF6QFGXTHSH",
                           "image": None,
                           "tags": ["machine_learning",
                                    "deep_learning",
                                    "image_processing",
                                    "sentiment_analysis",
                                    "sequential_models",
                                    "Coursera",
                                    "Matlab",
                                    "Stanford",
                                    "coursera",
                                    "Andrew_Ng"],
                           },
                          {"title": "Fundametals of scaleable data science by IBM",
                           "supertitle": "Coursera",
                           "group": "Online course",
                           "link": "https://www.coursera.org/account/accomplishments/records/FQQVAY93KBL8",
                           "image": None,
                           "tags": ["data_preparation",
                                    "deep_learning",
                                    "Spark",
                                    "Hadoop",
                                    "distributed_systems",
                                    "data_engineering"],
                           },
                          {"title": "Advanced Machine Learning and Signal Processing by IBM",
                           "supertitle": "Coursera",
                           "group": "Online course",
                           "link": "https://www.coursera.org/account/accomplishments/records/SNLKBKHQCC4L",
                           "image": None,
                           "tags": ['deep_learning',
                                    'machine_learning',
                                    'Spark',
                                    'IBM',
                                    'cloud',
                                    'distributed_systems',
                                    'IoT',
                                    'PySpark',
                                    'data_preparation'],
                           },
                          {"title": "Applied AI with Deep Learning by IBM",
                           "supertitle": "Coursera",
                           "group": "Online course",
                           "link": "https://www.coursera.org/account/accomplishments/records/2EFWV9L9B8EY",
                           "image": None,
                           "tags": ['deep_learning',
                                    'machine_learning',
                                    'Spark',
                                    'IBM',
                                    'cloud',
                                    'distributed_systems',
                                    'SparkML',
                                    'PySpark'],
                           },
                          {"title": "Codewars",
                           "group": "Online course",
                           "link": "https://www.codewars.com/users/hof.and.or",
                           "image": None,
                           "tags": ['challenge',
                                    'community',
                                    'Python',
                                    'learning',
                                    'game',
                                    'continuous_learning'],
                           },
                          {"title": "DataCamp",
                           "group": "Online course",
                           "link": "https://www.datacamp.com/profile/hofandor",
                           "image": None,
                           "tags": ['data_science',
                                    'Python',
                                    'machine_learning',
                                    'online_learning',
                                    'continuous_learning',
                                    'data_visualization',
                                    'data_engineering'],
                           },
                          {"title": "IPMA",
                           "subtitle": "Project management course and certificate",
                           "group": "Certificate",
                           "link": "https://www.linkedin.com/company/ipma-international-project-management-association/",
                           "image": None,
                           "tags": ['project_management',
                                    'IPMA',
                                    'PM_theory',
                                    'PM_practice',
                                    'certificate',
                                    'PM',
                                    'BUTE'],
                           },
                          {"title": "LabView",
                           "subtitle": "Associate Developer certificate",
                           "group": "Certificate",
                           "link": "https://sine.ni.com/nips/cds/view/p/lang/hu/nid/14438",
                           "image": None,
                           "tags": ['LabVIEW',
                                    'CLAD',
                                    'certificate',
                                    'programming',
                                    'visual_programming'],
                           },
                          {"title": "RobonAut 1st place (2016)",
                           "group": "Academic project",
                           "link": "https://bsstudio.hu/video/robonaut-2016-kozvetites",
                           "image": None,
                           "tags": ['LabVIEW',
                                    'CLAD',
                                    'certificate',
                                    'programming',
                                    'visual_programming'],
                           },
                          ],
             "groups": {"Studies":
                            {"text_color": "white",
                             "bg_color": "rgb(100,2,240)"},
                        "Online course":
                            {"text_color": "white",
                             "bg_color": "rgb(153, 0, 255)"},
                        "Certificate":
                            {"text_color": "white",
                             "bg_color": "rgb(204, 51, 0)"},
                        "Personal project":
                            {"text_color": "white",
                             "bg_color": "rgb(255,255,255)"},
                        "Academic project":
                            {"text_color": "white",
                             "bg_color": "green"},
                        "Professional project":
                            {"text_color": "white",
                             "bg_color": "rgb(255,255,255)"}
                        }
             }

if __name__ == "__main__":
    import json
    from helper_functions import load_json_portfolio

    portfolio_path = "portfolio.json"

    # Write out the JSON file
    with open(portfolio_path, "w") as f:
        f.write(json.dumps(portfolio))

    # Test: if the written file is the same as the read back
    assert load_json_portfolio(portfolio_path) == portfolio
